#
# Partial pooling example
#

library(tidyverse)
library(tidybayes)

simulate_data <- function(N, G) {
  # Sample group means
  beta <- rnorm(G, 0, 0.1)
  
  # Some groups are less likely to be sample from than others 
  group <- sample(1:G, replace = TRUE, size = N, prob = 1 / 1:G)
  
  # Sample outcomes
  y <- rnorm(N, mean = beta[group], sd = 1)
  
  list(
    beta = beta,
    N = N,
    G = G,
    y = y,
    group = group
  )
}

set.seed(1533)
stan_data <- simulate_data(100, 15)

plot(x = stan_data$group, y = stan_data$y)

#
# model_no_pooling.stan and model_partial_pooling.stan
# are both auto-generated by the script generate_models.sh
# using stanmerge
#
model_no_pooling <- cmdstan_model("./model_no_pooling.stan")
model_partial_pooling <- cmdstan_model("./model_partial_pooling.stan")

fit_no_pooling <- model_no_pooling$sample(data = stan_data)
fit_partial_pooling <- model_partial_pooling$sample(data = stan_data)

plot_beta_posterior <- function(fit, data) {
  fit$draws("beta") %>%
    spread_draws(beta[group]) %>%
    ggplot(aes(x = group, y = beta)) +
    geom_point(data = tibble(group = data$group, y = data$y), aes(y = y, color = "Observations"), alpha = 0.5) +
    geom_point(data = tibble(group = 1:data$G, y = data$beta), aes(y = y, color = "True group mean"), shape = 15) +
    stat_eye(alpha = 0.5, size = 0, shape = 4)
}

plot_beta_posterior(fit_no_pooling, stan_data)
plot_beta_posterior(fit_partial_pooling, stan_data)