name: Release
on:
  release:
    types: 
      - created

jobs:
  release:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            artifact: stanmerge-linux-x86_64
          - os: macos-latest:
            artifact: stanmerge-macos-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.1

      - name: Update opam repo
        run: opam update

      - name: Install dependencies
        run: |
          opam install . --deps-only --working-dir lib/stanc3
          opam install . --deps-only 

      - run: opam exec -- dune build bin/main.exe

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _build/default/bin/main.exe
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
